apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: pythonapp
  name: pythonapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: pythonapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: pythonapp
    spec:
      containers:
      - image: registry.iutbeziers.fr/pythonapp:latest
        name: pythonapp
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: pythonapp
  name: pythonapp
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "leastconn"
    haproxy.org/pod-maxconn: "50"
spec:
  selector:
    run: pythonapp
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
spec:
  rules:
  - host: pythonapp.172.18.0.5.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: pythonapp
          servicePort: 80

